AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-go

  Sample SAM Template for sam-app-go

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  registScoreFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image

      FunctionName: 'registScore'
      Policies: AmazonDynamoDBFullAccess
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /score
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMODB_ENDPOINT: ''
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: registScore/
      Dockerfile: Dockerfile

  getScoreFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image

      FunctionName: 'getScore'
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /people/{personID}/score
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: getScore/
      Dockerfile: Dockerfile

  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Score
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        WriteCapacityUnits: 2
        ReadCapacityUnits: 2
      AttributeDefinitions:
        - AttributeName: PersonID
          AttributeType: S
        - AttributeName: TestID
          AttributeType: S
      KeySchema:
        - KeyType: HASH
          AttributeName: PersonID
        - KeyType: RANGE
          AttributeName: TestID

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  registScoreAPI:
    Description: 'API Gateway endpoint URL for Prod environment for First Function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/score/'
  registScoreFunction:
    Description: 'First Lambda Function ARN'
    Value: !GetAtt registScoreFunction.Arn

  getScoreAPI:
    Description: 'API Gateway endpoint URL for Prod environment for First Function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/people/{personID}/score/'
  getScoreFunction:
    Description: 'First Lambda Function ARN'
    Value: !GetAtt getScoreFunction.Arn
